version: '3'

services:
  flask-api:
    build: .
    command: python -u src/app.py
    ports:
      - "5000:5000"
    volumes:
      - .:/app
    links:
      - mongo-db
  mongo-db:
    image: mongo:latest
    hostname: host_mongodb
    environment:
      - MONGO_INITDB_DATABASE=my_mongo_db
      - MONGO_INITDB_ROOT_USERNAME=root
      - MONGO_INITDB_ROOT_PASSWORD=pass
    ports:
      - 27017:27017